### ISSUE TITLE
Valor da lista na altera quando eu altero o limit nos parâmetros iniciais

### ISSUE THREAD

**Issue by Nandolinhares** [igordrangel/koala-angular-template#10]
![image](https://user-images.githubusercontent.com/15971419/107809811-769de980-6d4a-11eb-9a16-5b2ddf942af0.png)
O limit está 10, a lista está exibindo corretamente os 10, porém o valor ali fica fixo em 30. Se eu altero para outros valores, ele continua mostrando os 10 e não os valores corretos.

**Comment by Nandolinhares** [comment]
Correção para já #Marciodisse

**Comment by igordrangel** [comment]
Opa, obrigado pela sugestão! Foi implementada esta nova funcionalidade e estará disponível na versão 11.2.18.

Para uso da funcionalidade siga conforme abaixo:

![image](https://user-images.githubusercontent.com/34841323/107816097-03e53c00-6d53-11eb-96e7-1870b2fa9e62.png)

Esta especificação também encontra-se na documentação acessando https://koalaui.igordrangel.com.br/components/list
