### ISSUE TITLE
Erro ao ordenar uma lista com o Koala

### ISSUE THREAD

**Issue by Nandolinhares** [igordrangel/koala-angular-template#8]
![image](https://user-images.githubusercontent.com/15971419/107565702-b5a13300-6bc2-11eb-8853-bbdf42a0f0ca.png)
A lista não está ordenando quando clico nas setas de ordenação

**Comment by igordrangel** [comment]
Opa, o koala não realiza a ordenação nativamente, você quem deve realizar esta ordenação.

caso a lista seja do tipo **onDemand** a ordenação deverá ser feita pelo seu back-end...o koala na definição do **service** da lista retorna um filter do tipo **Observable**, que você pode capturar antes de realizar a requisição.

![image](https://user-images.githubusercontent.com/34841323/107570063-cc965400-6bc7-11eb-8f2d-9f1bf97ab9ee.png)

porém, se a lista for do tipo **all** você poderá capturar o filtro no mesmo local apresentando anteriormente e ordenar localmente com alguma biblioteca ou com o próprio JavaScript.
